### PR TITLE
feature/77

### PR DESCRIPTION
**Pull request by mj-blockydevs**

### CODE REVIEW

**Comment by zed-wong** [comment]
@mj-blockydevs @jasuwienas-blockydevs vercel deployment failed, pls fix

**Comment by mj-blockydevs** [comment]
@zed-wong I've adjusted arbitrage related page style to match the one from the mockups. Do we need to support something else in this task?

**Comment by zed-wong** [comment]
> @zed-wong I've adjusted arbitrage related page style to match the one from the mockups. Do we need to support something else in this task?

The new page looks good, I think now it's fine, let's focus on https://github.com/Hu-Fi/Mr.Market/issues/82, I will handle the rest

**Review by zed-wong — APPROVED** [review]

**Comment by zed-wong** [comment]
> > @zed-wong I've adjusted arbitrage related page style to match the one from the mockups. Do we need to support something else in this task?
> 
> The new page looks good, I think now it's fine, let's focus on #82, I will handle the rest

I identified some bug for the snapshot handler, now working on fixing it. will pr real quick

**Pull request merged**
