### PR TITLE
Updated memo design, add dynamic supported trading pairs and growdata

### PR DESCRIPTION
**Pull request by zed-wong**
- Updated the memo design to a hex-based format to include the maximum amount of information; this is the same mechanism used by Pando and MTG.  
- Added a SimplyGrow listener to handle "create SimplyGrow order" events.  
- Added dynamic trading pair endpoints at `/spot/data` and `/grow/data`.  
- Added the ability to modify supported trading pairs for spot, arbitrage (arb), market making (mm), and SimplyGrow in the admin page.  
- Added a carousel to the `/home` UI to make the presence of market making more prominent.  
- Added infinite loading to the `/market/token` page, supporting the loading of 250 additional tokens per iteration, up to a total of 2000 tokens.  
- Added support for handling cases of zero balances and 1-3 assets on the `/wallet` page.  
- Simplified the `/home` page by limiting the amount of market data displayed to 15 tokens for improved loading speed.  
- Fixed the issue of the iOS bottom navigation being too low.  
- Fixed the issue where a new user's avatar was not displayed on the `/home` page.  
- Consolidated the migration script into a single file.  
- Added additional tests for each service and controller file.

### CODE REVIEW

**Comment by zed-wong** [comment]
Fixing tests now

**Comment by zed-wong** [comment]
We will need to add "migration:seed" in pre run deployment script after merge

**Comment by zed-wong** [comment]
I will add a doc to illustrate about how the new memo encoding/decoding works

**Review by leric7 — APPROVED** [review]
Approving UI changes

**Pull request merged**
